server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: gateway-service
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://127.0.0.1:*"
              - "http://localhost:*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      discovery:
        locator:
          enabled: true

      routes:
        - id: ms-tool-service
          uri: lb://ms-tool-service
          predicates:
            - Path=/api/tools/**

        - id: ms-client-service
          uri: lb://ms-client-service
          predicates:
            - Path=/api/clients/**
