apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
type: Opaque
data:
  # Los valores deben estar en base64
  # echo -n "sisph-backend" | base64
  client-id: IHNpc3BoLWJhY2tlbmQ=
  # echo -n "2ehz06Qxwbn2gIKeOEgVdScIAtmG1ihi" | base64
  client-secret: MmVoejA2UXh3Ym4yZ0lLZU9FZ1ZkU2NJQXRtRzFpaGk=