apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
type: Opaque
data:
  # Los valores deben estar en base64
  # echo -n "sisph-backend" | base64
  client-id: IHNpc3BoLWJhY2tlbmQ=
  # echo -n "bshmLIgKCJQG4t5t1xg2a7nErt2A2Cbt" | base64
  client-secret: YnNobUxJZ0tDSlFHNHQ1dDF4ZzJhN25FcnQyQTJDYnQ=